CREATE TABLE public.conta (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	data_pagamento date NULL,
	data_vencimento date NOT NULL,
	descricao varchar(255) NOT NULL,
	situacao char(9) NOT NULL,
	valor numeric(38, 2) NOT NULL
);
